config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :user_bets
  resources :bet_options
  resources :payments
  resources :bets do
    collection do
      get 'export', as: 'export'
    end
  end

  resources :users
  # post 'users/new' => 'users#new'

  get '/', to: 'home#index', as: 'home'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Navbar paths
  root 'home#index'

  # Comments
  # post
  resources :comments
  resources :friends

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bet.rb
# == Schema Information
#
# Table name: bets
#
#  id             :integer          not null, primary key
#  execution_date :datetime
#  description    :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  visible        :boolean          default("true")
#  name           :string
#  avatar         :string
#

class Bet < ApplicationRecord
  has_many :bet_options, :dependent => :destroy
  has_many :user_bets, :through => :bet_options
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :bet_options
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :execution_date, timeliness: { on_or_after: lambda { Date.current }, type: :date }

  after_save :automanage_execution

  def get_total
    amount = 0
    self.user_bets.each do |ub|
      amount = amount + ub.amount
    end
    amount
  end

  def winners
    win = self.bet_options.where(win: true)
    st = ""
    win.each do |q|
      st = st + q.id.to_s + " ; "
    end
    st[0...-3]
  end

  def short_description
    #byebug
    unless description[0..30] == description
      auxiliar = description
      auxiliar2 = description[0..30]
      truncated = auxiliar[31] == ' ' || auxiliar2[30] == ' '
      unless truncated
        text = auxiliar2.split(/ /)
        text.pop
        return text.join(' ') + ' ...'
      end
    end
    description
  end

  private
    def automanage_execution
      self.delay(run_at: execution_date).finish_bet_second_ver
    end

    def finish_bet_second_ver
      winner_bet_opts = self.bet_options.find_by(win: true).first

      winner_user_bets = winner_bet_opts.user_bets

      winner_bets_per_user = Hash.new(0)

      total_in_winner_bets = 0

      winner_user_bets.each do |w_ub|
        winner_bets_per_user[w_ub.user] += w_ub.amount
        total_in_winner_bets += w_ub.amount
      end

      # Rates to multiply the winner's pool later.
      winner_rate_per_user = Hash.new(0)

      winner_bets_per_user.each do |user, bet|
        winner_rate_per_user[user] = bet / total_in_winner_bets
        puts(bet / total_in_winner_bets)
      end

      total_money_waged_on_bet = 0

      self.user_bets.each do |u_bet|
        total_money_waged_on_bet += u_bet.amount
      end

      commision = 0.05 # 5% commision

      puts("The house gets #{commision * total_money_waged_on_bet}")

      total_money_to_give_out = total_money_waged_on_bet * (1 - commision)

      puts("A total of #{total_money_to_give_out} will be given out to winners")

      winner_rate_per_user.each do |user, rate|
        user.balance += total_money_to_give_out * rate
        user.save

        puts("#{total_money_to_give_out * rate} was given to #{user.name}")
      end
    end

    # To be run after a bet's execution date has been reached.
    def finish_bet
      bet_options.each do |op|
        op.user_bets.each do |ub|
          if op.win
            amount = ub.amount * ub.percentage
            us = ub.user
            us.amount = us.amount + amount
            us.save
            Notification.create(message: "La apuesta #{self.name} ha finalizado.Tu apuesta de #{ub.amount} por #{ub.bet_option.description} ha salido ganadora ", user: ub.user)
          else
            Notification.create(message: "La apuesta #{self.name} ha finalizado.Tu apuesta de #{ub.amount} por #{ub.bet_option.description} ha perdido ", user: ub.user)
          end
        end
      end
      self.user_bets.each do |usr_bet|
        UserMailer.bet_finished(usr_bet.user, self).deliver_now
      end
    end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  include BetsHelper
  include FriendsHelper
  include SessionsHelper
  include UsersHelper

  before_action :setup_bet_displays, only: [:show, :edit, :update, :destroy]
  # before_action :set_bet, only: [:show, :edit, :update, :destroy]

  # before_action :check_privacy, only: [:show, :edit, :update, :destroy]

  # GET /bets
  # GET /bets.json
  def index
    @bets_friends = bets_owned_by_friends_of(current_user)
    @bets_public = bets_public_and_not_owned_by_friends_or_user(current_user)
    @bets = Bet.all unless current_user.user_type.zero?
    @bets = Bet.where(visible: true).or(Bet.where(user_id: Friend.where(friend_id:current_user.id).pluck(:user_id))) if current_user.user_type.zero?
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
    redirect_to home_path, notice: 'Bet not found' unless @bet.present?
  end

  # GET /bets/new
  def new
    @bet = Bet.new
    @bonos = @bet.bet_options#1.times { @bet.bet_options.build }
  end

  # GET /bets/1/edit
  def edit
    @bonos = @bet.bet_options
    redirect_to home_path, notice: 'Bet not found' unless @bet.present?
  end

  def export
    # Nombre de la apuesta
    # Autor o entidad relacionada a la apuesta
    # Fecha de inicio
    # Fecha de termino
    # Cantidad de apostantes
    # Suma total apostada por los apostantes
    # Opcion ganadora de la apuesta
    @bets = Bet.all unless current_user.user_type.zero?
    @bets = Bet.where(visible: true).or(Bet.where(user_id: Friend.where(friend_id:current_user.id).pluck(:user_id))) if current_user.user_type.zero?
    respond_to do |format|
      format.xls
    end

  end

  # POST /bets
  # POST /bets.json
  def create
    aux = params
    params[:bet_options].each do |meh|
      if params[:bet_options]["#{meh}"]["win"].count == 2
        params[:bet_options]["#{meh}"]["win"] = "true"
      else
        params[:bet_options]["#{meh}"]["win"] = "false"
      end
    end
    aux[:bet][:bet_options_attributes] = params[:bet_options]
    aux[:bet][:bet_options_attributes].delete("{index}")
    aux.delete("bet_options")
    aux = aux.require(:bet).permit(:name , :execution_date,:avatar, :description, :remove_avatar, :visible, bet_options_attributes: [:description, :percentage, :win, :id])
    @bet = Bet.new(aux)
    #FIXME: It works, but only for GMT -4
    @bet.execution_date+=60*60*4
    @bet.user = current_user
    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, flash: { success: 'Bet was successfully created.' } }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    aux = params
    params[:bet_options].each do |meh|
      if params[:bet_options]["#{meh}"]["win"].count == 2
        params[:bet_options]["#{meh}"]["win"] = "true"
      else
        params[:bet_options]["#{meh}"]["win"] = "false"
      end
    end
    aux[:bet][:bet_options_attributes] = params[:bet_options]
    aux[:bet][:bet_options_attributes].delete("{index}")
    aux.delete("bet_options")
    aux = aux.require(:bet).permit(:name , :execution_date,:avatar ,:description, bet_options_attributes: [:description, :percentage, :win, :id])
    @bet.attributes(aux)
    @bet.execution_date+=60*60*4
    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bet }
      else
        #puts @bet.errors.full_messages
        format.html { render :edit }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def setup_bet_displays
      set_bet
      #check_privacy
    end

    def check_privacy
      if(!admin_access? && !do_I_have_access?(current_user, @bet.user))
          redirect_to bets_url
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      if current_user.present?
        @bet = Bet.find_by(id: params[:id])
      else
        @bet = nil
      end
    end

    def

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:name, :execution_date, :description, :avatar, :visible, bets_options_attributes: [:description, :percentage, :win])
    end
end

app/helpers/bets_helper.rb
module BetsHelper
include FriendsHelper

	def all_the_bets
		Bet.all
	end

	def bets_where_user_participates(user)
		Bet.where(id: BetOption.where(id: UserBet.where(user_id:user.id).pluck(:bet_option_id)).pluck(:bet_id))
	end

	def bets_of(user)
		Bet.where(user_id: user.id)
	end

	def bets_owned_by_friends_of(user)
		Bet.where(user_id: Friend.where(friend_id:user.id).pluck(:user_id))
	end

	def bets_public_and_not_owned_by_friends_or_user(user)
		Bet.where(visible: true) - bets_of(user) - bets_owned_by_friends_of(user)
	end

	def bets_private_and_not_owned_by_friends_or_user(user)
		Bet.where(visible: false) - bets_of(user) - bets_owned_by_friends_of(user)
	end

	def do_I_have_access?(me, owner)
		are_we_both_friends?(me, owner) ||
		me == @bet.user 
	end

	def is_this_bet_open?
		@bet.execution_date > Time.now
	end

	def get_winner_options
		@bet.bet_options.where(win: :true).first.description
	end
end

app/views/bets/_comment.html.haml
%div
  %h4= "#{comment.user.name}:"
  %p.text_with_linebreaks= comment.content
  %br/

app/views/bets/_form.html.haml
-content_for :errors do
  - if @bet.errors.any?
    #error_explanation
      .alert.alert-danger.fade.in
        %span.closebtn{"data-dismiss" => "alert"} ×
        %h2
          =#t('errors.template.header', :count => supplier.errors.count, :model => Supplier.model_name.human)
        %ul
          - @bet.errors.full_messages.each do |message|
            %li= message
- content_for :content do
  = form_for @bet, html: {class:"content_like"} do |f|

    %fieldset.UI_column
      %h1
        - if @bet.name?
          = t('title.editing') + '...'
        - else
          = t('title.creating_a') + '...'
      %h2
        = t('title.bet_parameters')
      %br/
      %ul.UI_form_column
        %li
          = f.label :execution_date
          -if bet.execution_date.present?
            %input#datetimepicker4{:type => "text", :value => @bet.execution_date.in_time_zone("Santiago").strftime('%Y/%m/%d %H:%M'), name: 'bet[execution_date]'}
          -else

            %input#datetimepicker4{:type => "text", :value => Time.now.in_time_zone("Santiago").strftime('%Y/%m/%d %H:%M'), name: 'bet[execution_date]'}
        %br/
        %li
          = f.label :name
          = f.text_field :name
        %br/
        %li

          = f.label :description
        = f.cktext_area :description

        %br/
        %li
          = f.label :avatar
          = f.file_field :avatar, class: "UI_button"
        %br/
        %li
          - if @bet.avatar?
            = f.label :remove_avatar
            = f.check_box :remove_avatar
            = image_tag @bet.avatar.thumb.url
        %li
          = f.label :visible, t('label.make_it_private')
          = f.check_box :visible, {:checked => !@bet.visible},
                   0,
                   1
        %br/
    %fieldset.UI_column
      %ul.UI_form_column
        %h1
          - if @bet.name?
            = t('title.bet_no', bet_id: @bet.id)
          - else
            = t('title.new_bet') + '.'
        %h2
          = t('title.bet_options')
        %br/
        .row.additional_info
          .meh
            .doh{style: "display:inline-block"}
              %h4
                = t('title.description')
              = text_field_tag "bet_options[{index}][description]",nil, class: 'form-control', placeholder: t('placeholder.bet_option_description')
            .doh{style: "display:inline-block"}
              %h4
                = t('title.winner_option')
              = check_box "bet_options[{index}][win]",nil, class: 'form-control'
            .doh{style: "display:inline-block"}
              .field
                %button.addAdditionalInfo.tiny.UI_button{start_at: 0, target: ".additional_infos", type:"button"}
                  = t('button.add')
                %button.red.deleteAdditionalInfo.tiny.UI_button_negative{style:"display:none", type:"button"}
                  = t('button.delete')

        -begin
          .additional_infos
            - @bonos.each_with_index do |b,index|
              .row.additional_info
                .field{style: "display:none"}
                  = text_field_tag "bet_options[#{index}][id]", b.id, class: 'form-control',style: "display:none"
                .field{style: "display:inline-block"}
                  = text_field_tag "bet_options[#{index}][description]", b.description, class: 'form-control'
                .doh{style: "display:inline-block"}
                  %h4{style:"visibility:hidden; height: 0px;"}
                    = t('title.winner_option')
                  = check_box "bet_options[#{index}][win]",'',checked: b.win, class: 'form-control'
                .field{style: "display:inline-block"}

                  %button.red.deleteAdditionalInfo.tiny.UI_button_negative{type:"button"}
                    = t('button.delete')

        -rescue

        - bet.bet_options do |b|
          .field
            = text_field_tag "bet_options[#{index}][description]", b.name, class: 'form-control'
          .check_box
            = t('button.delete')

        = f.submit t('button.accept'), class: "UI_button"

  :javascript
    $(function() {
      var delete_additional_info;
      delete_additional_info = function() {
        return $(".deleteAdditionalInfo").click(function() {
          var row;
          row = $(this).parents(".additional_info");
          return row.remove();
        });
      };
      delete_additional_info();
      return $(".addAdditionalInfo").click(function() {
        var index, new_row, row;
        index = $(this).attr("start_at");
        row = $(this).parents(".additional_info");
        new_row = row.clone().prependTo($(this).attr("target"));
        new_row.find("input").each(function() {
          return $(this).attr("name", $(this).attr("name").replace("{index}", index));
        });
        new_row.find(".deleteAdditionalInfo").show();
        new_row.find(".addAdditionalInfo").hide();
        new_row.find("h4").css('visibility', 'hidden');
        new_row.find("h4").css('height', '0px');
        delete_additional_info();
        $(this).attr("start_at", parseInt(index) + 1);
        return row.find("input").val("");
      });
    });
  :javascript
    /*
      window.onerror = function(errorMsg) {
      $('#console').html($('#console').html()+'<br>'+errorMsg)
      }*/

      $.datetimepicker.setLocale('es');


      $('#datetimepicker4').datetimepicker({
        //allowTimes:['12:00','13:00','15:00','17:00','17:05','17:20','19:00','20:00'],
        //formatDate:'d.m.Y',
        step:1
      });
      $('#open').click(function(){
      $('#datetimepicker4').datetimepicker('show');
     });
      $('#close').click(function(){
      $('#datetimepicker4').datetimepicker('hide');
      });
      $('#reset').click(function(){
      $('#datetimepicker4').datetimepicker('reset');
      });



      $('#datetimepicker_dark').datetimepicker({theme:'dark'})

app/views/bets/_user_bet.html.haml
%div
  %h4= "#{user_bet.user.name}:"
  %p.text_with_linebreaks= user_bet.bet_option
  %p.text_with_linebreaks= user_bet.amount
  %br/

app/views/bets/edit.html.haml
%h1 Editing Bet
= render 'form', bet: @bet
= link_to t('link.show'), @bet
|
= link_to t('link.back'), bets_path

app/views/bets/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name=<%= t('excel.bets') %>>
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.name_of_bet') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.owner') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.starting_date') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.closing_date') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.total_wagered') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.winner_options') %></Data></Cell>
      </Row>
    <% @bets.each do |bet| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= bet.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= bet.name %></Data></Cell>
        <%- if bet.user.present? %>
          <Cell><Data ss:Type="Number"><%= bet.user.id %></Data></Cell>
          <%- else %>
          <Cell><Data ss:Type="String"><%= t('excel.unregistered_user') %></Data></Cell>
        <% end %>
        <Cell><Data ss:Type="String"><%= bet.created_at.to_s %></Data></Cell>
        <Cell><Data ss:Type="String"><%= bet.execution_date %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= bet.get_total %></Data></Cell>
        <Cell><Data ss:Type="String"><%= bet.winners %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
  <Worksheet ss:Name=<%= t('excel.bet_options') %>>
    <Table>
      <Row>
        <Cell><Data ss:Type="String"><%= t('excel.bet_id') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.option_id') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.description') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t('excel.winner') %></Data></Cell>
      </Row>
    <% @bets.each do |bet| %>
      <% bet.bet_options.each do |option| %>
        <Row>
          <Cell><Data ss:Type="Number"><%= bet.id %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= option.id %></Data></Cell>
          <Cell><Data ss:Type="String"><%= option.description %></Data></Cell>
          <%- if option.win %>
          <Cell><Data ss:Type="String"><%= t('excel.yes') %></Data></Cell>
          <%- else %>
          <Cell><Data ss:Type="String"><%= t('excel.no') %></Data></Cell>
          <% end %>
        </Row>
      <% end %>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/bets/index.html.erb
<html>
  <head>
    <!-- Nothing here yet -->
  </head>
  <body>
    <% content_for :content do %>

      <% the_rest_of_bets = all_the_bets %>

      <div class="UI_column">
        <h1> <%= t('title.your_bets') %> </h1>
        <ul>
          <% for bet in current_user.bets %>
            <li><%= link_to bet.name, bet_path(bet) %> </li>
          <% end %>
        </ul>
      </div>

      <div class="UI_column">
        <h1><%= t('title.friends_bets') %></h1>
        <i><%= t('subtitle.and_of_peeps_whove_added_u_as_friend') %></i>
        <br>
        <br>
        <ul>
          <% for friend in who_added_me(current_user) %>
            <li>
              <h2><%= t('title.USER_s', user: friend.name) %></h2>
              <ul>
                <% for bet in friend.bets %>
                  <li><%= link_to bet.name, bet_path(bet) %> </li>
                <% end %>
              </ul>
              <br>
            </li>
          <% end %>
        </ul>
      </div>

      <% all_the_other_public_ones = bets_public_and_not_owned_by_friends_or_user(current_user) %>
      <% the_rest_of_bets = bets_private_and_not_owned_by_friends_or_user(current_user) %>

      <div class="UI_column">

        <% if admin_access? %>
          <h1><%= t('title.other_bets') %></h1>
        <% else %>
          <h1> <%= t('title.other_public_bets') %> </h1>
          <br>
        <% end %>

        <% if all_the_other_public_ones != [] %>
          <h2><%= t('title.public_bets') %></h2>
          <ul>
            <% for bet in all_the_other_public_ones %>
              <li><%= link_to bet.name, bet_path(bet) %> </li>
            <% end %>
          </ul>
        <% end %>

        <% if admin_access? && the_rest_of_bets != [] %>

          <p><% the_rest_of_bets %></p>

          <h2><%= t('title.private_bets') %></h2>
          <ul>
            <% for bet in the_rest_of_bets  %>
              <li><%= link_to bet.name, bet_path(bet) %> </li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <div class="UI_column">
          <h1> <%= t('title.excel_export') %> </h1>
          <ul>
        <li><%= link_to "Excel", export_bets_path(format: "xls") %></li>
        </ul>
      </div>
    
    <% end %>
  </body>
</html>

app/views/bets/index.html.haml
%p#notice= notice
%h1 Bets
.index_bets{style: "padding-left:20%; padding-right:20%;"}
  %table
    %thead
      %tr
        %th Execution date
        %th Description
        %th{:colspan => "3"}
    %tbody
      - @bets.each do |bet|
        %tr
          %td= bet.execution_date
          %td= bet.description
          %td= link_to 'Show', bet
          %td= link_to 'Edit', edit_bet_path(bet)
          %td= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to "Excel", export_bets_path(format: "xls")
  = link_to 'New Bet', new_bet_path

app/views/bets/new.html.haml
%h1 New Bet
= render 'form', bet: @bet
= link_to 'Back', bets_path

app/views/bets/show.html.erb
<% content_for :content do %>
  <div class="UI_column">
    <h1><%= @bet.name %></h1>
    <%= image_tag bet_medium @bet %>
    <br>

    <% if(!@bet.visible) %>

    <!-- TODO: make this distinct from the Bet's description -->

      <i> <%= t('subtitle.this_bet_is_private') %> </i>

      <% if(!admin_access?) %>

        <% if(@bet.user == current_user) %>

          <i> <%= t('subtitle.that_means_that_yadayada') %> </i>

        <% else %>

          <i> <%= t('subtitle.as_friend_of_yadayada') %> </i>

        <% end %>

      <% else %>

        <i> <%= t('subtitle.as_admin_yadayada') %> </i>

      <% end %>

      <br>

    <% end %>

    <div class="desc_textbox">
      <i class="text_with_linebreaks"><%= @bet.description.html_safe %></i>
    </div>
    <br>
    <br>

    <h2>
      <% tleft = @bet.execution_date - Time.zone.now %>
      <% tWords = distance_of_time_in_words(Time.zone.now, @bet.execution_date)%>
      <%= tleft > 0 && t('title.bet_is_due_in_WORDS', tWords: tWords) || t('title.bet_is_over') %>
    </h2>

    <% if @bet.user == current_user %>
      <p> <%= t('subtitle.this_bet_was_placed_by_u') %> <%= link_to t('subtitle.here'), edit_bet_url(@bet) %></p>
    <% else %>
      <p><%= t('subtitle.this_bet_was_placed_by_other') %>  <%= link_to @bet.user.name, user_url(@bet.user) %></p>
    <% end %>
  </div>

  <div class="UI_column">
    <h1><%= t('title.options') %> </h1>
    <%= render @bet.bet_options %>
  </div>

  <div class="UI_column">
    <h1> <%= t('title.users_comments') %> </h1>
    <br>
    <div id="comments_container">
      <%= render @bet.comments %>
    </div>
    <%= form_for(:comment, url: comments_path, remote: true, html:{id: 'comment_form'}) do |f| %>
      <strong> <%= t('smalltitle.comment') %>: </strong>
      <br>
      <%= f.text_area :content, required: true %>
      <%= f.text_field :bet_id, :value => @bet.id, style: "display: none;" %>
      <%= f.text_field :user_id, :value => current_user.id, style: "display: none;" %>
      <br/>
      <%= f.submit t('button.post'), class: "UI_button" %>
    <% end %>
  </div>

  <div class="UI_column">
    <h1><%= t('title.users_bets') %> </h1>
    <br>
    <div id="bets_container">
      <%= render @bet.user_bets %>
    </div>
  </div>





<% end %>

app/views/bets/show.html.haml
-if notice.present?
  %p#notice= notice
.bet_container{style: "padding-left:20%; padding-right:20%;"}
  %h1{style: "font-size: 44	px;"}
    = @bet.name
  = image_tag bet_medium @bet
  %pre{style:"text-align: left; overflow:auto"}
    = @bet.description
  %h2
  = "Bet is due at #{@bet.execution_date}"
  %h2 Options
  =render @bet.bet_options
  %p
  = link_to 'Edit', edit_bet_path(@bet)
  |
  = link_to 'Back', bets_path

  %h2 Post a comment
  %br
  = form_for(:comment, url: comments_path) do |f|
    .field
      = "Comment: "
      = f.text_field :content, required: true
    .field
      = f.text_field :bet_id, :value => @bet.id, style: "display: none;"
    .field
      = f.text_field :user_id, :value => current_user.id, style: "display: none;"
    / .field
    /   = f.text_field :entry_id, :value => @entry.id, style: "display: none;"
    .actions
      = f.submit "Post"


  %h3 Comments
  -@bet.comments.each do |comment|
    .container.row{style:"border: 1px solid #eee;"}
      %h4
        ="#{comment.user.username}:"
      %h5
        =comment.content
    %br
  / = link_to 'Edit', edit_entry_path(@entry)
  / |
  / = link_to 'Atras', home_path