config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :user_bets
  resources :bet_options
  resources :payments
  resources :bets do
    collection do
      get 'export', as: 'export'
    end
  end

  resources :users
  # post 'users/new' => 'users#new'

  get '/', to: 'home#index', as: 'home'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Navbar paths
  root 'home#index'

  # Comments
  # post
  resources :comments
  resources :friends

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  username           :string(20)
#  email              :string
#  confirmation_token :string
#  confirmed_at       :string
#  user_type          :integer          default("0")
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  balance            :float            default("0.0")
#  name               :string
#  password_digest    :string
#  image              :string
#  activation_digest  :string
#  activated          :boolean          default("false")
#  activated_at       :datetime
#  gravatar_usage     :boolean          default("false")
#  access_token       :string
#

# For use with the Gravatar API
require 'digest/md5'

class User < ApplicationRecord
  attr_accessor :activation_token
  require 'digest'
  # Bcrypt imports
  has_secure_password

  # Validates
  validates :username, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :email, presence: true, uniqueness: true, format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :password, length: { in: 8..72 }, on: :create
  validates :balance, :numericality => { :greater_than_or_equal_to => 0}

  # Model relationships
  has_many :user_bets
  has_many :payments
  has_many :friends
  has_many :comments
  has_many :friends
  has_many :bets
  has_many :notifications
  # Triggers
  after_create  :send_activation_email
  before_create :create_activation_digest
  before_save   :downcase_email

  # Avatar uploader mounting
  mount_uploader :image, AvatarUploader

  # Methods

  ## Sends email with confirmation token to validate user
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end


  # Generates the gravatar URL for this user
  def gravatar_url
    hash = Digest::MD5.hexdigest(self.email)

    image_src = "//www.gravatar.com/avatar/#{hash}?d=identicon"
  end

  def self.gravatar_url email
    hash = Digest::MD5.hexdigest(email)

    image_src = "//www.gravatar.com/avatar/#{hash}?d=identicon"
  end



  def generate_access_token
    return 1 if self.access_token == '1'
    return 0 if self.access_token == '0'
    temporal = Time.now.to_s + email
    self.access_token = Digest::SHA256.hexdigest temporal
    self.save
    self.access_token
  end


  # private
    # To be able to use it and compare it easily
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include UsersHelper
include FriendsHelper
include BetsHelper
# include SessionsHelper

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  skip_before_action :check_logged_in, only: [:new, :create]

  before_action :admin_barrier, only: [:edit, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @friends = real_friends(@user)
    @private_bets = Bet.where(user: @user, visible: false)

    # if different_user? && only_he_is_friend?(current_user, @user) || are_we_both_friends?(current_user, @user)
    #   @private_bets = Bet.where(user: @user, visible: false)
    # else
    #   @private_bets = []
    # end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.gravatar_usage = true if request.format.json?
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url }
        format.json { render json:{message: 'Creacion exitosa', activate: edit_account_activation_url(@user.activation_token, email: @user.email)}, status: :ok, location: @user}
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Blocks edit and destroy access for non-admins.
    ## It allows self-edit and self-destruct, though.
    def admin_barrier
      unless admin_access? || logged_in? && current_user == @user
        flash[:alert] = "You must have admin access to do that."
        redirect_to :back
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      admin_access? && admin_user_filter || normal_user_filter
    end

    ## Helpers for user_params
    def normal_user_filter
      params.require(:user).permit(:username, :name, :email, :password, :image, :remove_image, :gravatar_usage)
    end
    def admin_user_filter
      params.require(:user).permit(:username, :name, :email, :password, :image, :remove_image, :gravatar_usage, :user_type)
    end
end

app/helpers/users_helper.rb
module UsersHelper
include SessionsHelper

  def admin_access?
  	logged_in? && current_user.user_type != 0
  end

  def user_type_string
  	admin_access? && t('header.admin_user') || t('header.normal_user')
  end

  def see_this_userS_type
    @user.user_type != 0 && t('header.admin_user') || t('header.normal_user')
  end

  def user_name
  	current_user.username
  end

  def private_view_access?
  	!different_user? || friends? || admin_access?
  end
end

app/views/users/_form.html.erb
<html>
  <head>
    <!-- Nothing here yet -->
  </head>
  <body>
    <% content_for :content do %>
      <div class="UI_column">
        <%= form_for(@user) do |f| %>
          <% if user.errors.any? %>
            <div id="error_explanation">
              <h2> <%= pluralize(user.errors.count, "error") %>
          prohibited this user from being saved:</h2>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </div>
          <% end %>

          <h1>
            <% if user.username? %>
              <%= t('title.editing_profile_of_USER', user: user.name) %>
            <% else %>
              <%= t('title.create_new_account') %>
            <% end %>
          </h1>

          <ul class="UI_form_column">
            <li><%= f.label :username  %> <%= f.text_field :username %></li>            
            <br>
            <li><%= f.label :name  %> <%= f.text_field :name %></li>            
            <br>
            <li><%= f.label :email  %> <%= f.text_field :email, id: "cur_email", oninput:"makeCurrentGravatar()"%>            
            </li>
            <br>
            <li><%= f.label :password  %> <%= f.password_field :password %>
            </li>
            <br>
            <li><%= f.label :image  %> <%= f.file_field :image, class: "UI_button" %>
            </li>
            <br>
            <li>
              <% if user.image? %>
                <%= f.label :remove_image %> <%= f.check_box :remove_image %>
                <%= image_tag user.image.thumb.url %>
              <% end %>
            </li>
            
            <br>
            <%= javascript_include_tag "javascripts/md5.min" %>
            <script type="text/javascript">
              function makeCurrentGravatar () {
                var mail = document.getElementById("cur_email").value;

                var hash = md5(mail);

                document.getElementById("cur_gravatar").src = "//www.gravatar.com/avatar/" + hash + "?d=identicon";
              }
            </script>
 
            <li>
              <%= f.label :gravatar_usage, t('label.use_gravatar_instead') %> <%= f.check_box :gravatar_usage %>
              <%= image_tag User::gravatar_url(@cur_email || ""), id:"cur_gravatar", onload:"makeCurrentGravatar()" %>
            </li>
            
            <li><%= f.submit t('button.accept'), class: "UI_button" %> <%= link_to t('link.have_an_account'), login_path unless @user.name %></li>

          </ul>          
        <% end %>
      </div>
    <% end %>
  </body>
</html>

app/views/users/_form.html.haml
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :image
    = f.file_field :image
    - if f.object.image?
      = image_tag f.object.image.thumb.url
      = f.label :remove_image
      = f.check_box :remove_image
  - if admin_access?
    .field
      = f.label "Admin"
      = f.check_box :user_type, {:class => "myclass", :style => "mystyle"}, 1, 0
  / .field
  /   = f.label :balance
  /   = f.number_field :balance
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.erb
<html>
  <head>
    <!-- Nothing here yet -->
  </head>
  <body>
    <% content_for :content do %>
      <div class="UI_column">
        <h1><%= t('title.your_friends') %></h1>
        <ul>
          <% for friend in real_friends(current_user) %>
            <li><%= link_to friend.name, user_path(friend) %> </li>
          <% end %>
        </ul>
      </div>

      <div class="UI_column">
        <h1><%= t('title.not_yet_friends') %></h1>
        <h2><%= t('title.you_ve_added_as_friend') %></h2>
        <ul>
          <% for friend in who_ive_added(current_user) - real_friends(current_user) %>
            <li><%= link_to friend.name, user_path(friend) %> </li>
          <% end %>
        </ul>
        <br>
        <h2><%= t('title.have_added_you') %></h2>
        <ul>
          <% for friend in who_added_me(current_user) - real_friends(current_user) %>
            <li><%= link_to friend.name, user_path(friend) %> </li>
          <% end %>
        </ul>
      </div>
      <div class="UI_column">
        <h1> <%= t('title.other_users') %> </h1>
        <ul>
          <% friends_ids = current_user.friends.select(:friend_id) %>
          <% non_friends = User.where.not(id: friends_ids) - [current_user] %>
          <% for other in non_friends %>
            <li><%= link_to other.name, user_path(other) %> </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </body>
</html>

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th Username
      %th Email
      / %th Confirmation token
      / %th Confirmed at
      %th Type
      %th Balance
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.email
        / %td= user.confirmation_token
        / %td= user.confirmed_at
        %td= user.user_type
        %td= user.balance
        -if current_user.user_type == 1 or user.id == current_user.id
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
=#   link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user, method: :create
= link_to 'Back', users_path

app/views/users/show.html.erb
<html>
  <head>
    <!-- Nothing here yet -->
  </head>
  <body>
    <% content_for :content do %>
      <div class="UI_column">
        <h1><%= @user.name %></h1>
        <br>
        <%= image_tag this_user_medium %>
        <br>
        <br>
        <div id="profile_box">
          <ul id="user_qualities">
            <li>
              <strong><%= t('smalltitle.type') %>: </strong> <%= see_this_userS_type %>
            </li>
            <li>
              <strong><%= t('smalltitle.username') %>: </strong> <%= @user.username %>
            </li>
            <% if !different_user? || are_we_both_friends?(@user, current_user) %>
              <li>
                <strong><%= t('smalltitle.email') %>: </strong> <%= @user.email %>
              </li>
              <li>
                <strong><%= t('smalltitle.balance') %>: </strong> <%= @user.balance %>
              </li>
            <% end %>
          </ul>
          <ul class="UI_link_column">
            <li><%= link_to t('link.edit'), edit_user_path(@user) %></li>
            <li><%= link_to t('link.back_to_users'), users_path %></li>
          </ul>
        </div>
      </div>
      <div class="UI_column">
        <h1><%= t('title.list_of_friends') %></h1>
        <ul id="real_friends">
          <% for friend in real_friends(@user) %>
            <li><%= link_to friend.name, user_path(friend) %> </li>
          <% end %>
        </ul>
        <br>
        <h1><%= t('title.public_bets') %></h1>
        <ul>
          <% for bet in @user.bets - @private_bets %>
            <li><%= link_to bet.name, bet_path(bet) %> </li>
          <% end %>
        </ul>
      </div>
      <% if different_user? %>
        <div class="UI_column">
          <h1><%= t('title.friendship_status') %></h1>
          <div id="friendship_status">
            <%= render(:partial => 'friends/form', :locals => { :user => @user }) %>
          </div>
          <br>
          <br>
          <h1><%= t('title.private_bets') %></h1>
          <div id= "private_bets">
            <% if are_we_both_friends?(current_user, @user) %>
              <ul>
              <!-- TODO: con AJAX ya no se muestran las bets privadas de tus amigos. -->
                <% if @private_bets != [] %>
                  <% for bet in @private_bets %>
                    <li>
                      <%= link_to "#{bet.name}", bet_path(bet) %>
                    </li>
                  <% end %>
                <% else %>
                  <p><%= t('subtitle.user_has_no_private_bets') %></p>
                <% end %>
              </ul>
            <% else %>
              <p><%= t('subtitle.u_dont_have_access_to_private') %></p>
            <% end %>
            </div>
        </div>
      <% end %>
    <% end %>
  </body>
</html>

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Username:
  = @user.username
- if private_view_access?
  %p
    %strong Email:
    = @user.email
%p
  %strong Avatar:
  %br
  = image_tag this_user_thumb
%p
  %strong Type:
  = see_this_userS_type
- if private_view_access?
  %p
    %strong Balance:
    = @user.balance
%p
  - if different_user?
    - if are_we_both_friends?(current_user, @user)
      %strong You are friends 😃
      %br
      %br
        = link_to "Delete friendship", friend_path(friends?) , class: "button red tiny", method: :delete

    - elsif only_I_am_friend?(current_user, @user)
      %strong They haven't accepted your friendship yet 😟
      %br
      %br
        = link_to "Remove friendship request", friend_path(friends?) , class: "button red tiny", method: :delete

    - elsif only_he_is_friend?(current_user, @user)
      %strong They have added you as friend 😃
      %br
      = form_for(:friendship, url: friends_path) do |f|
        .field
          = f.text_field :user_id, :value => current_user.id, style: "display: none;"
        .field
          = f.text_field :friend_id, :value => @user.id, style: "display: none;"
        .actions
          = f.submit "Accept friendship request!", class: 'button green tiny'
    - else
      %strong You are not friends 😟
      %br
      = form_for(:friendship, url: friends_path) do |f|
        .field
          = f.text_field :user_id, :value => current_user.id, style: "display: none;"
        .field
          = f.text_field :friend_id, :value => @user.id, style: "display: none;"
        .actions
          = f.submit "Become friends", class: 'button green tiny'


= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path