config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :user_bets
  resources :bet_options
  resources :payments
  resources :bets do
    collection do
      get 'export', as: 'export'
    end
  end

  resources :users
  # post 'users/new' => 'users#new'

  get '/', to: 'home#index', as: 'home'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Navbar paths
  root 'home#index'

  # Comments
  # post
  resources :comments
  resources :friends

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bet_option.rb
# == Schema Information
#
# Table name: bet_options
#
#  id          :integer          not null, primary key
#  description :string
#  bet_id      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  win         :boolean          default("false")
#  user_bet_id :integer
#

class BetOption < ApplicationRecord
  belongs_to :bet, required: false
  has_many :user_bets, dependent: :destroy
end

app/controllers/bet_options_controller.rb
class BetOptionsController < ApplicationController
  before_action :set_bet_option, only: [:show, :edit, :update, :destroy]

  # GET /bet_options
  # GET /bet_options.json
  def index
    @bet_options = BetOption.all
  end

  # GET /bet_options/1
  # GET /bet_options/1.json
  def show
  end

  # GET /bet_options/new
  def new
    @bet_option = BetOption.new
  end

  # GET /bet_options/1/edit
  def edit
  end

  # POST /bet_options
  # POST /bet_options.json
  def create
    @bet_option = BetOption.new(bet_option_params)
    @bet_option.user = current
    respond_to do |format|
      if @bet_option.save
        format.html { redirect_to @bet_option, notice: 'Bet option was successfully created.' }
        format.json { render :show, status: :created, location: @bet_option }
      else
        format.html { render :new }
        format.json { render json: @bet_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bet_options/1
  # PATCH/PUT /bet_options/1.json
  def update
    respond_to do |format|
      if @bet_option.update(bet_option_params)
        format.html { redirect_to @bet_option, notice: 'Bet option was successfully updated.' }
        format.json { render :show, status: :ok, location: @bet_option }
      else
        format.html { render :edit }
        format.json { render json: @bet_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bet_options/1
  # DELETE /bet_options/1.json
  def destroy
    @bet_option.destroy
    respond_to do |format|
      format.html { redirect_to bet_options_url, notice: 'Bet option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet_option
      @bet_option = BetOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_option_params
      params.require(:bet_option).permit(:description, :bet_id)
    end
end

app/helpers/bet_options_helper.rb
module BetOptionsHelper
	def total_amount_bet_on(bet_opt)
		total = 0
		bet_opt.user_bets.each do |u_bet|
			total += u_bet.amount
		end
		total
	end

	def is_this_bet_opt_winner?(bet_opt)
		bet_opt.win
	end

end

app/views/bet_options/_bet_option.html.erb
<!-- <p class="notice"><%=notice%></p> -->

<h2> <%= bet_option.description %> </h2> 


<% if is_this_bet_open? %>
	<%= form_for(:user_bet, url: user_bets_path, remote: true) do |f| %>
		<strong><%= t('label.amount')%>:</strong> <%= f.text_field :amount, required: true %>
	    <%= f.text_field :user_id, :value => current_user.id, style: "display: none;" %>
	    <%= f.text_field :bet_option_id, :value => bet_option.id, style: "display: none;" %>
	    <br>
	    <%= f.submit t('smalltitle.bet'), class: "UI_button" %>
	<% end %>
<% else %>
	<!-- Total apostado -->
	<strong>Total apostado: </strong> <%= total_amount_bet_on(bet_option)%>
	<!-- Ganadora? -->
	<% if is_this_bet_opt_winner?(bet_option) %>
		<br>
		<h3>Ganadora!</h3>
	<% else %>
		<br>
	<% end %>

<% end %>
<br>

app/views/bet_options/_bet_option.html.haml
.bet_optio_continer
  %p{style: "display:inline-block; margin: 15px"}
    %strong Description:
    = bet_option.description
  .doh{style: "display:inline-block"}
    = form_for(:user_bet, url: user_bets_path) do |f|
      .doh{style: "display:inline-block"}
        .field
          %strong Amount:
          = f.text_field :amount
      .field{style: "display: none;"}
        = f.text_field :user_id, :value => current_user.id, style: "display: none;"
      .field{style: "display: none;"}
        = f.text_field :bet_option_id, :value => bet_option.id, style: "display: none;"
      .doh{style: "display:inline-block"}
        .actions{style: "display:inline-block"}
          = f.submit 'Wager', style: "display:inline-block"

app/views/bet_options/_form.html.haml
= form_for(bet_option) do |f|
  - if bet_option.errors.any?
    #error_explanation
      %h2
        = pluralize(bet_option.errors.count, "error")
        prohibited this bet_option from being saved:
      %ul
        - bet_option.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :bet_id
    = f.text_field :bet_id
  .actions
    = f.submit

app/views/bet_options/edit.html.haml
%h1 Editing Bet Option
= render 'form', bet_option: @bet_option
= link_to t('link.show'), @bet_option
|
= link_to t('link.back'), bet_options_path

app/views/bet_options/index.html.haml
%p#notice= notice
%h1 Bet Options
%table
  %thead
    %tr
      %th Description
      %th Bet
      %th{:colspan => "3"}
  %tbody
    - @bet_options.each do |bet_option|
      %tr
        %td= bet_option.description
        %td= bet_option.bet
        %td= link_to 'Show', bet_option
        %td= link_to 'Edit', edit_bet_option_path(bet_option)
        %td= link_to 'Destroy', bet_option, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Bet Option', new_bet_option_path

app/views/bet_options/new.html.haml
%h1 New Bet Option
= render 'form', bet_option: @bet_option
= link_to 'Back', bet_options_path

app/views/bet_options/show.html.haml
%p#notice= notice
%p
  %strong 
  	= t('title.description') + ":"
  = @bet_option.description
%br/
%p
  %strong 
  	= t('smalltitle.bet') + ":"
  = @bet_option.bet
= link_to 'Edit', edit_bet_option_path(@bet_option)
|
= link_to 'Back', bet_options_path