config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :user_bets
  resources :bet_options
  resources :payments
  resources :bets do
    collection do
      get 'export', as: 'export'
    end
  end

  resources :users
  # post 'users/new' => 'users#new'

  get '/', to: 'home#index', as: 'home'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Navbar paths
  root 'home#index'

  # Comments
  # post
  resources :comments
  resources :friends

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/layout_helper.rb
module LayoutHelper
	
	def cp(path)
		"current" if current_page?(path)
	end

	def cc(c)
		"current" if controller_name == c
	end
	
	def random_quote
		if I18n.locale == :en
			[
				"Quit while you’re ahead. All the best gamblers do.", 
				"Eat your betting money, but never bet your eating money.",
				"Show me a wealthy gambler and I’ll show you a man who made his fortune from something other than gambling.",
				"A dollar won is twice as sweet as a dollar earned.",
				"Remember this: The house doesn’t beat the player. It just gives him an opportunity to beat himself.",
				"Fortune knocks at every man's door once in a lifetime, but in a good many cases the man is in a neighboring saloon and does not hear her.",
				"Luck is what happens when preparation meets opportunity.",
				"If you must play, decide three things when you start: the rules, the stakes of the game, and the quitting time.",
				"Scared money never wins.",
				"If you ain't just a little scared when you enter a casino, you are either very rich or you haven't studied the games enough.",
				"The subject of gambling is all encompassing. It combines man's natural play instinct with his desire to know about his fate and his future.",
				"Depend on the rabbit's foot if you will, but remember it didn't work for the rabbit.",
				"One of the healthiest ways to gamble is with a spade and a package of garden seeds."
				].sample
		elsif I18n.locale == :es 
			[
				"Renuncia mientras vas ganando, todos los buenos apostadores lo hacen.",
				"Come con el dinero que apuestas, pero nunca apuestes el dinero con el que comes.",
				"Muéstrame un apostador rico y te mostraré un hombre que creó su fortuna de algo más que las apuestas.",
				"Un dólar ganado es dos veces más dulce que un dólar trabajado.",
				"Recuerda esto: la casa no vence al jugador, sólo le da una oportunidad para vencerse a sí mismo.",
				"La suerte golpea a la puerta de todo hombre una vez en la vida, pero en muchos casos éste está bebiendo en un bar cercano y no la escucha golpear.",
				"Suerte es lo que pasa cuando la preparación se encuentra con la oportunidad.",
				"Si tienes que jugar, decide tres cosas al comenzar: las reglas, qué apostarás y en qué momento te retirarás.",
				"Un jugador asustado nunca gana.",
				"Si no estás siquiera un poco asustado cuando entras a un casino, o eres muy rico o no has estudiado los juegos lo suficiente.",
				"La apuesta, como tema, es muy incluyente: combina el instinto natural del hombre de jugar y su deseo de saber sobre su destino y su futuro.",
				"Depende de la pata del conejo si quieres, pero recuerda que no le sirvió al conejo.",
				"Una de las formas más sanas de apostar es con una pala y un paquete de semillas."
				].sample
		else
			"I do not speak this locale."
		end
	end
end

app/views/layouts/_banner.html.erb
<div id="bannerTitle">
  <h1> The bet~ter app. </h1>
</div>

app/views/layouts/_footer.html.erb
<ul id="footer">

  <li id="authors_notice">

    <%= link_to "The bet-ter App!", home_path %> <%= t('footer.by') %> <a href="https://github.com/IIC2513-2017-1/grupo-18">Grupo 18</a> (Félix Fischer <%= t('footer.and') %> Felipe Rojos)</li>

  <li id="footer_nav">

    <button class="button_dressed_like_link" id="aboutLink", type="button"><%= t('footer.about')%></button>
    <!-- <span>|</span> -->
    <%= mail_to "sppt.grupo.18.web@gmail.com",
    	t('footer.contact')  %>
    <!-- <span>|</span> -->

    <%= link_to t('footer.change_locale'), { :locale => t('footer.next_locale')}, id: "localeLink" %>

  </li>
</ul>

<div id="aboutModal" class="modal">
	<div class="modal-content">
		<span class="close">&times;</span>
	<% if I18n.locale == :en %>
		<h1><a id="About_Better_App_0"></a>About Bet~ter App!</h1>
		<h2><a id="Us_2"></a>Us</h2>
		<p>Hi! We’re Félix Fischer and Felipe Rojos, otherwise known as <strong>Grupo 18</strong>.</p>
		<h2><a id="Our_vision_6"></a>Our vision</h2>
		<p>We believe in a clean and secure web, with honest services and centered in the user experience. We do not use tracking software, and from day 0 we’ve always been honest about the prizes’ percentage we take out of every bet to pay our bills.</p>
		<h2><a id="Technologies_we_use_10"></a>Technologies we use</h2>
		<p>We built our site on top of <strong><em>Ruby on Rails</em></strong>, <strong><em>HTML5</em></strong>, <strong><em>CSS3</em></strong> and <strong><em>JavaScript (ECMA v6)</em></strong>. There is full detail on this under the Appendix at the end.</p>
		<h2><a id="Ending_thoughts_14"></a>Ending thoughts</h2>
		<p>We hope you enjoy our service. Have a good one, and may the Lady of Fortune pick your odds.</p>
		<br>
		<hr>
		<br>
		<h2><a id="Appendix_tools_we_used_20"></a>Appendix: tools we used</h2>
		<h3><a id="Important_Libraries_and_Gems_22"></a>Important Libraries and Gems</h3>
		<p>We use the <code>bcrypt</code> library for password security and <code>SASS</code> for augmenting CSS’ usability.</p>
		<p>We use the gem <code>CarrierWave</code> for photo uploading and <code>minimagick</code> for resizing. We use <code>Ckeditor</code> for rich text input, <code>delayed_job</code> for scheduling of delayed tasks and <code>httparty</code> for our interaction with REST APIs.</p>
		<h3><a id="Designer_Resources_28"></a>Designer Resources</h3>
		<p>We used Paletton to help us pick the color scheme of the site. <a href="http://paletton.com/palette.php?uid=75x0u0kleqtbzEKgVuIpcmGtdhZ">Here</a> is our palette.</p>
		<p>We also use the following Google Fonts:</p>
		<ul>
		<li><a href="https://fonts.google.com/specimen/Merienda">Merienda</a> for the banner and <a href="https://fonts.google.com/specimen/Clicker+Script/">Clicker Script</a> for the gambling quotes,  because of their inspiring beauty.</li>
		<li><a href="https://fonts.google.com/specimen/Poly">Poly</a> for interactive UI elements, because of its good readability and elegant serif styling.</li>
		<li><a href="https://fonts.google.com/specimen/Vollkorn">Vollkorn</a> for all the headings, and <a href="https://fonts.google.com/specimen/Lato">Lato</a> for the rest of the content. We picked these because of their warmth, and because Lato complements Vollkorn’s strength with its soft style.</li>
		</ul>
		<h3><a id="Web_APIs_used_by_this_site_37"></a>Web APIs used by this site</h3>
		<p>We are currently using two REST APIs:</p>
		<ul>
		<li>We consume the <a href="https://en.gravatar.com/site/implement/">Gravatar API</a> to enhance our user’s customization experience, and</li>
		<li>The <a href="http://mindicador.cl/">Mindicador API</a> to display real-time currency information to our international users.</li>
		</ul>
	<% elsif I18n.locale == :es %>
		<h1><a id="Acerca_de_Better_App_0"></a>Acerca de Bet~ter App!</h1>
		<h2><a id="Nosotros_2"></a>Nosotros</h2>
		<p>Hola! Somos Félix Fischer y Felipe Rojos, también conocidos como <strong>Grupo 18</strong>.</p>
		<h2><a id="Nuestra_visin_6"></a>Nuestra visión</h2>
		<p>Nosotros creemos en una web limpia y segura, con servicios honestos y centrados en la experiencia de usuario. Nosotros no usamos software de rastreo y siempre hemos sido transparentes respecto al porcentaje de los pozos de apuestas que recojemos para pagar nuestras cuentas.</p>
		<h2><a id="Tecnologas_que_usamos_10"></a>Tecnologías que usamos</h2>
		<p>Construímos nuestro sitio sobre <strong><em>Ruby on Rails</em></strong>, <strong><em>HTML5</em></strong>, <strong><em>CSS3</em></strong> y <strong><em>JavaScript (ECMA v6)</em></strong>. Todas nuestras comunicaciones se realizan sobre <strong><em>HTTPS</em></strong>.</p>
		<p>Puede encontrar más detalle sobre nuestro <em>web stack</em>, en el Apéndice al final del texto.</p>
		<h2><a id="ltimas_palabras_16"></a>Últimas palabras</h2>
		<p>Esperamos que disfrute de nuestro servicio. Páselo bien, y que la Dama de la Fortuna sea quien tire sus dados.</p>
		<hr>
		<h2><a id="Apndice_herramientas_que_usamos_22"></a>Apéndice: herramientas que usamos</h2>
		<h3><a id="Libreras_y_gemas_importantes_24"></a>Librerías y gemas importantes</h3>
		<p>Nosotros usamos la librería <code>bcrypt</code> para autenticar y proteger las contraseñas de las cuentas y <code>SASS</code> para facilitar el uso de CSS.</p>
		<p>Usamos la gema <code>CarrierWave</code> para subida de fotos y <code>minimagick</code> para elegir su tamaño. Usamos <code>Ckeditor</code> para capturar texto enriquecido, <code>delayed_job</code> para programar acciones a futuro y <code>httparty</code> para interactuar con APIs REST.</p>
		<p>Finalmente, usamos la gema <code>i18n</code> para implementar regionalización.</p>
		<h3><a id="Herramientas_de_diseo_32"></a>Herramientas de diseño</h3>
		<p>Usamos <em>Paletton</em> para elegir la paleta de colores del sitio. <a href="http://paletton.com/palette.php?uid=75x0u0kleqtbzEKgVuIpcmGtdhZ">Aquí</a> podéis ver nuestra paleta en detalle.</p>
		<p>También usamos las siguientes tipografías de <em>Google Fonts</em>:</p>
		<ul>
		<li><a href="https://fonts.google.com/specimen/Merienda">Merienda</a> para el banner y <a href="https://fonts.google.com/specimen/Clicker+Script/">Clicker Script</a> para las citas de juerga,  por su inspiradora belleza.</li>
		<li><a href="https://fonts.google.com/specimen/Poly">Poly</a> para elementos interactivos de la interfaz de usuario, por su excelente legibilidad y su elegante estilo serifado.</li>
		<li><a href="https://fonts.google.com/specimen/Vollkorn">Vollkorn</a> para todas las cabeceras, y <a href="https://fonts.google.com/specimen/Lato">Lato</a> para el resto del contenido. Elegimos ambas por su calidez y porque se complementa muy bien la fuerza de <em>Vollkorn</em> con el estilo suave de <em>Lato</em>.</li>
		</ul>
		<h3><a id="Web_APIs_usadas_en_este_sitio_41"></a>Web APIs usadas en este sitio</h3>
		<p>Actualmente, usamos dos APIs REST:</p>
		<ul>
		<li>La <a href="https://en.gravatar.com/site/implement/">API de Gravatar</a> para mejorar la experiencia de personalización de la app, y</li>
		<li>La <a href="http://mindicador.cl/">API de Mindicador</a> para mostrar información monetaria en tiempo real a nuestros usuarios internacionales.</li>
		</ul>
	<% end %>
		<br>
	</div>
</div>

<script type="text/javascript">
	var modal = document.getElementById("aboutModal");

	var btn = document.getElementById("aboutLink");

	var modCnt = document.getElementsByClassName("modal-content")[0];

	btn.onclick = function() {
		modal.style.display = "block";
	}

	var clsBtn = document.getElementsByClassName("close")[0];

	clsBtn.onclick = function() {
		resetModal();
	}

	window.onclick = function(event) {
		if(event.target == modal)
		{
			resetModal();
		}
	}

	function resetModal() {
		modCnt.scrollTop = 0;
		modal.style.display = "none";
	}

</script>

app/views/layouts/_header.html.erb
<ul id="header">
  <% if logged_in? %>
    <li id="log_status">
      <strong class="tooltip_bearer"> 
        <%= user_type_string %> 
        <span class="tooltip">Tooltip text</span>
      </strong>
      <span></span>
      <i> <%= user_name %> </i>
    </li>
    <li>
      <%= link_to t('header.home'), root_path, class: cc("home") %>
    </li>
    <li class="dropdown">
      <%= link_to t('header.users'), users_path, class: cc("users") %>
          
      <ul class="dropdown-content">
        <li><%= link_to t('header.all_m'), users_path, class: cp("/users") %></li>
        <li><%= link_to t('header.me'), user_url(current_user), class: cp(user_url(current_user)) %></li>
      </ul>
    </li>
    <% if admin_access? %>
      <li class="dropdown">
        <%= link_to t('header.payments'), payments_path, class: cc("payments") %>
        
        <ul class="dropdown-content">
          <li><%= link_to t('header.all_m'), payments_path, class: cp("/payments") %></li>
          <li><%= link_to t('header.new_m'), new_payment_path, class: cp("/payments/new") %></li>
        </ul>     
      </li>
    <% end %>
    <li class="dropdown">
      <%= link_to t('header.bets'), bets_path, class: cc("bets") %>
      <ul class="dropdown-content">
        <li><%= link_to t('header.all_f'), bets_path, class: cp("/bets") %></li>
        <li><%= link_to t('header.new_f'), new_bet_path, class: cp("/bets/new") %></li>
      </ul>    
    </li>
    <li><%= link_to t('header.log_out'), logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to t('header.log_in'), login_path, class: cp("/login")  %></li>
    <li><%= link_to t('header.sign_up'), new_user_path, class: cp("/users/new") %></li>
  <% end %>

  <li style="margin-left: auto; margin-right: 0.5%;">
      <ul class="header_like">
        <% cache("last_money_values", expires_in: 12.hours) do %>
          <li><%= "UF: $#{get_uf}" %></li>
          <li><%= "USD: $#{get_dolar}" %></li>
          <li><%= "€: $#{get_euro}" %></li>
          <li><%= "UTM: $#{get_utm}" %></li>
        <% end %>
      </ul>  
  </li>

</ul>

app/views/layouts/_header.html.haml
%body
  .nav_container
    %nav
      - if logged_in?
        %strong.nav= user_type_string
        %i.nav= user_name
      - else

      %li.nav= link_to "Home",   root_path
      %li.nav= link_to "Users",   users_path
      - if logged_in?
        %li.nav= link_to "Payments", payments_path
        %li.nav= link_to "New bet", new_bet_path
        %li.nav= link_to "Log out", logout_path, method: :delete
      - else
        %li.nav= link_to "Log in", login_path        
  %br/

app/views/layouts/_quote.html.erb
<div id="bannerQuote">
	<i><%= random_quote %></i>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <link href='https://fonts.googleapis.com/css?family=Merienda' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Clicker Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Poly' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
    <title>The Bet~ter App!</title>
    <meta author="Grupo 18" />
    <%= csrf_meta_tags%>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>
  <body>
    <div id="container">
      <div id="upper">
        <div id="banner">
          <%= render 'layouts/banner' %>
          <%= render 'layouts/quote' %>
        </div>
        <%= render 'layouts/header' %>
      </div>
      <div id="errors">
        <%- #byebug %>
        <%- if flash.any? %>
          <%- flash.each do |name, msg| %>
            <div class= "<%= name %>">
              <span class='closebtn'>×</span>
              <b><%=msg%></b>
            </div>
          <%- end %>
        <%- end %>
        <%= yield :errors %>
      </div>
      <div id="notifications">
        <%- #byebug %>
        <%- if current_user.present? %>
          <%- current_user.notifications.each do |n| %>
            <div class= "notice">
              <span class='closebtn'>×</span>
              <b><%=n.message%></b>
              <%-n.destroy%>
            </div>
          <%- end %>
        <%- end %>
      </div>
      <div id="content">
        <%= yield :content %>
      </div>

      <%= render 'layouts/footer' %>
      <script>
      $(".closebtn").click(function(){this.parentElement.style.display='none';});
      </script>
    </div>
  </body>
</html>